=== SteelRazor47/medusa-plugin-tolgee/package/src/admin/i18n/translations/$schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "loading": {
            "type": "string"
        },
        "shippingOptionsList": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "empty": {
                    "type": "string"
                }
            },
            "required": [
                "title",
                "empty"
            ]
        },
        "productOptionsList": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "empty": {
                    "type": "string"
                }
            },
            "required": [
                "title",
                "empty"
            ]
        },
        "widget": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "subtitleEmpty": {
                    "type": "string"
                },
                "notTranslated": {
                    "type": "string"
                },
                "add": {
                    "type": "string"
                },
                "syncAll": {
                    "type": "string"
                },
                "selectLanguage": {
                    "type": "string"
                }
            },
            "required": [
                "title",
                "subtitle",
                "subtitleEmpty",
                "notTranslated",
                "add",
                "syncAll",
                "selectLanguage"
            ]
        }
    },
    "required": [
        "$schema",
        "shippingOptionsList",
        "widget",
        "loading"
    ],
    "additionalProperties": false
}

=== SteelRazor47/medusa-plugin-tolgee/package/src/admin/i18n/translations/it.json
{
    "$schema": "./$schema.json",
    "shippingOptionsList": {
        "title": "Traduzioni",
        "empty": "Non sono ancora presenti traduzioni."
    },
    "productOptionsList": {
        "title": "Traduzioni opzioni",
        "empty": "Non sono ancora presenti traduzioni."
    },
    "widget": {
        "title": "Traduzioni",
        "subtitle": "Per tradurre, premi ALT+click sul valore.",
        "subtitleEmpty": "Non sono ancora presenti traduzioni.",
        "notTranslated": "Non tradotto (premi ALT + click qui)",
        "add": "Aggiungi",
        "syncAll": "Sincronizza tutto",
        "selectLanguage": "Seleziona lingua"
    },
    "loading": "Caricamento..."
}
